# Steven VanOmmeren

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(7,7)
print(tensor_1)

tensor([[0.8018, 0.9947, 0.3489, 0.9602, 0.7087, 0.2855, 0.2563],
        [0.1747, 0.7739, 0.1388, 0.5465, 0.9845, 0.3386, 0.3062],
        [0.3861, 0.2792, 0.0907, 0.3112, 0.1741, 0.4400, 0.1399],
        [0.3518, 0.9435, 0.4474, 0.8834, 0.5301, 0.4741, 0.9736],
        [0.5208, 0.9820, 0.8542, 0.1928, 0.7679, 0.3480, 0.6504],
        [0.4169, 0.6075, 0.7478, 0.8766, 0.3980, 0.7559, 0.4640],
        [0.1941, 0.5661, 0.6313, 0.3721, 0.6648, 0.3261, 0.8981]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_2 = torch.rand(1,7)

# Perform matrix multiplication 
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
print(tensor_3)

tensor([[3.0879],
        [2.2538],
        [1.1044],
        [3.2519],
        [2.6637],
        [2.4789],
        [2.3330]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)

# Matrix multiply tensors
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
print(tensor_3)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
tensor_1 = torch.rand(2,3).to("cuda")
tensor_2 = torch.rand(2,3).to("cuda")

print(f"Tensor 1:\n{tensor_1}\n")
print(f"Tensor 2:\n{tensor_2}\n")

True
Tensor 1:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

Tensor 2:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')




### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
print(tensor_3)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
tensor_1_max = torch.max(tensor_3)

# Find min
tensor_1_min = torch.min(tensor_3)

print(f"Max value: {tensor_1_max:.4f}, Min value: {tensor_1_min:.4f}")

Max value: 0.5617, Min value: 0.3647


### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
tensor_1_argmax = torch.argmax(tensor_3).item()

# Find arg min
tensor_1_argmin = torch.argmin(tensor_3).item()

print(f"Argmax: {tensor_1_argmax}, Argmin: {tensor_1_argmin}")

Argmax: 3, Argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_2 = tensor_1.squeeze()

# Print out tensors and their shapes
print(f"Tensor 1: {tensor_1} {tensor_1.shape} \nTensor 2:\n{tensor_2} {tensor_2.shape}")

Tensor 1: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10]) 
Tensor 2:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
